language: python
python:
  - "3.8"

install:
  - cd mysite
  - pip install -r requirements.txt

script:
  - black ./
  - flake8 --max-line-length=130 --ignore=F405,F403,F541,W503,E231,E722
  - coverage run -a --source="." manage.py test

after_success:
  coveralls