language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - black ./
  - flake8 --max-line-length=130 --ignore=F405,F403,F541,W503,E231,E722
  - coverage run -a --source="." mysite/manage.py test

after_success:
  coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA5RHF3MBNLJWYWJPG
  secret_access_key: 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
  region: us-east-1
  app: swe1-app
  env: venv
  bucket_name: elasticbeanstalk-us-east-1-930342461530
  on:
    branch: main
